name: output events on issues
on: issues
jobs:
  output event details:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
  output issue event & github context:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue event & github context
        run: |
          echo "Full Event Payload: ${{ toJson(github.event) }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"